version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
      dotnet: 8.0
    commands:
      - echo Installing backend dependencies...
      - cd api
      - dotnet restore
      - echo Installing frontend dependencies...
      - cd ../frontend
      - npm install

  pre_build:
    commands:
      - echo Running pre-build commands...

  build:
    commands:
      - echo Building backend...
      - cd ../api
      - dotnet build --configuration Release
      - echo Building frontend...
      - cd ../frontend
      - npm run build

  post_build:
    commands:
      - echo Build completed successfully.

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: frontend/build

cache:
  paths:
    - '/root/.nuget/packages/**/*'
    - 'frontend/node_modules/**/*'