version: 0.2

phases:
  install:
    commands:
      - apt-get update
      - apt-get install -y nginx
  build:
    commands:
      - echo "Creating /var/www/html directory..."
      - mkdir -p /var/www/html
      - echo "Copying all files to /var/www/html..."
      - cp -R * /var/www/html/
      - echo "Files in /var/www/html after copying:"
      - ls -R /var/www/html
  post_build:
    commands:
      - echo "Starting Nginx to serve the static site..."
      # - systemctl start nginx
      - echo "Nginx is now serving your static site on port 80"
artifacts:
  files:
    - index.html
    - '**/channel-pictures/**'
    - '**/icons/**'
    - '**/thumbnails/**'
    - '**/styles/**'
  discard-paths: no
  base-directory: /var/www/html